# Generated by Django 3.0.6 on 2020-05-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_create_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
