# Generated by Django 3.0.6 on 2020-05-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_add_approvals_to_submissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='username',
            new_name='designer',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='friend_code',
            new_name='designer_code',
        ),
    ]
