# Generated by Django 3.0.6 on 2020-05-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_add_design_type_and_normalize_names'),
    ]

    operations = [
        migrations.RenameModel('Submission', 'Design')
    ]
