# Generated by Django 3.0.6 on 2020-05-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_fix_design_type_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='designer',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='designer_code',
            new_name='creator_code',
        ),
    ]
