# Generated by Django 3.0.6 on 2020-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20200512_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='design',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
