# Generated by Django 3.0.6 on 2020-05-15 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20200512_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
