# Generated by Django 3.0.6 on 2020-05-17 18:21

import acdesignhub.hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20200517_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='original_image',
            field=models.ImageField(max_length=1024, upload_to=acdesignhub.hub.models._upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=acdesignhub.hub.models._upload_path),
        ),
    ]
