# Generated by Django 3.0.6 on 2020-05-19 14:05
import re

from django.db import migrations

def _format_my_code(value):
    part1 = value[0:2]
    part2 = value[2:6]
    part3 = value[6:10]
    part4 = value[10:14]
    return "-".join([part1, part2, part3, part4])

def _format_codes(apps, schema_editor):
    Design = apps.get_model('hub', 'Design')
    for design in Design.objects.all():
        if not re.match('MO(-[0-9ABCDEFGHJKLMNPQRSTUVWXY]{4}){3}', design.design_code):
            design.design_code = _format_my_code(design.design_code)
        if not re.match('MA(-[0-9]{4}){3}', design.creator_code):
            design.creator_code = _format_my_code(design.creator_code)
        design.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20200517_1821'),
    ]

    operations = [
        migrations.RunPython(
            _format_codes, elidable=True
        )
    ]
