# Generated by Django 3.0.6 on 2020-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_migrate_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_name',
            field=models.CharField(max_length=20),
        ),
    ]
